@baseUrl = http://localhost:3000

#Messages
###List all messages
GET {{baseUrl}}/message/
?limite=10
&offset=10
&user=gabriel
###List only one message
GET {{baseUrl}}/message/1
###Create a message
#For testing whiteList: true
POST {{baseUrl}}/message/
Content-Type: application/json

{
    "text": "Uai",
    "from": "Josh",
    "bla": "bla", 
    "to": "Ane",
    "read": false,
    "date": "2025-04-07T22:03:37.623Z"
}

###Update a message
PATCH {{baseUrl}}/message/2/
Content-Type: application/json

{
    "text": "Updated message",
    "from": "Josh",
    "to": "Ane",
    "read": false,
    "date": "2025-04-07T22:03:37.623Z"
}

###Delete a message
DELETE {{baseUrl}}/message/abc/